### ISSUE TITLE
Create an email plugin

### ISSUE THREAD

**Issue by mashton** [metagov/metagov-prototype#61]
* Add a plugin that has an `action` for sending an email. This is for the Agreement Engine https://github.com/metagov/agreements-prototype.
* Metagov already has a Mailgun account that we use for our Discourse server, so maybe we should use that. Mailgun: https://documentation.mailgun.com/en/latest/api-sending.html#sending
* Plugin tutorial: https://docs.metagov.org/en/latest/plugin_tutorial.html

**Comment by lukvmil** [comment]
added in pull request #72

**Comment by lukvmil** [comment]
Looks like there were some errors in the build, I will look into it

**Comment by lukvmil** [comment]
Merged into master, closing this issue!
